version: '3.1'

services:
  influxdb:
    image: influxdb:1.8
    restart: always
    hostname: influxdb
    ports:
      - 8086:8086
    networks:
      - ignet

  grafana:
    image: grafana/grafana
    restart: always
    hostname: grafana
    ports:
      - 3000:3000
    networks:
      - ignet

networks:
  ignet:
    driver: bridge
